In [1]:
import pandas as pd

# 1. Create the initial list of 4 students
data = {
    'ID': [101, 102, 103, 104],
    'Name': ['Kato', 'Gerald', 'Alice', 'Bob'],
    'Status': ['Active', 'Active', 'Active', 'Active'],
    'Course': ['Python', 'Data Science', 'Math', 'Physics']
}

# Create the DataFrame (your registration system)
df_students = pd.DataFrame(data)

print("System Ready! Initial 4 students loaded.")
df_students

System Ready! Initial 4 students loaded.

    ID    Name  Status        Course
0  101    Kato  Active        Python
1  102  Gerald  Active  Data Science
2  103   Alice  Active          Math
3  104     Bob  Active       Physics

In [4]:
# --- A. ADD a new student ---
new_student = {'ID': 105, 'Name': 'Sarah', 'Status': 'Active', 'Course': 'Engineering'}
df_students = pd.concat([df_students, pd.DataFrame([new_student])], ignore_index=True)

# --- B. DELETE students who left (e.g., Bob ID 104) ---
# We filter the list to only keep those who HAVEN'T left
df_students = df_students[df_students['ID'] != 104]

# --- C. UPDATE recent information (e.g., Gerald changed course) ---
df_students.loc[df_students['Name'] == 'Gerald', 'Course'] = 'Advanced Data Science'

# --- D. LIST the students to see the changes
print("\n--- UPDATED STUDENT REGISTER ---")
print(df_students)

--- UPDATED STUDENT REGISTER ---
    ID    Name  Status                 Course
0  101    Kato  Active                 Python
1  102  Gerald  Active  Advanced Data Science
2  103   Alice  Active                   Math
3  105   Sarah  Active            Engineering
4  105   Sarah  Active            Engineering

In [3]:
df_students.to_csv('final_student_register.csv', index=False)

In [7]:
df_students.loc[df_students['Name'] == 'Gerald', 'Course'] = 'Teaching'
df_students

    ID    Name  Status       Course
0  101    Kato  Active       Python
1  102  Gerald  Active     Teaching
2  103   Alice  Active         Math
3  105   Sarah  Active  Engineering
4  105   Sarah  Active  Engineering

In [ ]:
import os
os.getcwd()